spring:
  application:
    name: chat-api
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_DATABASE:chat}
    username: chat_owner
    password: password
    driver-class-name: org.postgresql.Driver
